# Data Encoding

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [ ]:
# Create a simple dataframe
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [ ]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

# One_Hot_Encoding

In [ ]:
#create an instance of OneHotEncoder
encoder=OneHotEncoder()

In [ ]:
encoded=encoder.fit_transform(df[['color']]).toarray()

In [ ]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [ ]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [ ]:
encoder.transform([['blue']]).toarray()

/home/ad/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [ ]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

# Label Encoder

In [ ]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [ ]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [ ]:
lbl_encoder.fit_transform(df[['color']])

/home/ad/miniconda3/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

# Ordinal Encoding

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [ ]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [ ]:
emcoder=OrdinalEncoder(categories=[['small','meidum','large']])

In [ ]:
encoder.fit_transform(df[['size']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 3)>

In [ ]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [ ]:
encoder.transform([['small']])

/home/ad/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1 stored elements and shape (1, 3)>