# Data Encoding

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
# Create a simple dataframe
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [4]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

# One_Hot_Encoding

In [5]:
#create an instance of OneHotEncoder
encoder=OneHotEncoder()

In [6]:
encoded=encoder.fit_transform(df[['color']]).toarray()

In [7]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [8]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [9]:
encoder.transform([['blue']]).toarray()

/home/ad/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [10]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

# Label Encoder

In [11]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [12]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [13]:
lbl_encoder.fit_transform(df[['color']])

/home/ad/miniconda3/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

# Ordinal Encoding

In [14]:
from sklearn.preprocessing import OrdinalEncoder

In [15]:
df=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [16]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [17]:
emcoder=OrdinalEncoder(categories=[['small','meidum','large']])

In [18]:
encoder.fit_transform(df[['size']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 3)>

In [19]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [20]:
encoder.transform([['small']])

/home/ad/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1 stored elements and shape (1, 3)>

# Target Guided Ordinal Encoding

-> It is a technique used to encode categorical variable based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categorical variable with a large number of unique categories and we want to use this variable as a feature in our machine learning model.

In [21]:
import pandas as pd

In [22]:
df=pd.DataFrame({
    'city':['New York','London','Paris','Tokyo','New York','Paris'],
    'price':[200,150,200,250,180,320]
})

In [23]:
df

       city  price
0  New York    200
1    London    150
2     Paris    200
3     Tokyo    250
4  New York    180
5     Paris    320

In [27]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [25]:
df

       city  price
0  New York    200
1    London    150
2     Paris    200
3     Tokyo    250
4  New York    180
5     Paris    320

In [28]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 260.0, 'Tokyo': 250.0}

In [29]:
df['city_encoded']=df['city'].map(mean_price)

In [30]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    200         260.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         260.0

In [32]:
df[['price','city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    200         260.0
3    250         250.0
4    180         190.0
5    320         260.0